$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - "node_modules"
  - "/.git"
  - "/.gitignore"
  - "/.husky"
  - "/.jest-results"
  - "/.markdownlint.yaml"
  - "/.prettierrc.yaml"
  - "/.vscode/extensions.json"
  - "/.vscode/settings.json"
  - "/cspell.project-words.txt"
  - "/dist"
  - "/docs/javascripts/algebra-*.js"
  - "/docs/params.json"
  - "/docs/stylesheets/modern-normalize.css"
  - "/docs/stylesheets/pygment_trac.css" # spellchecker:ignore pygment_trac
dictionaryDefinitions:
  - name: project-words
    path: "./cspell.project-words.txt"
    addWords: true
dictionaries: ["project-words"]
ignoreWords: []
flagWords: []
