source 'https://rubygems.org'

gem "jekyll", "~> 4.4"
gem "kramdown-parser-gfm", "~> 1.1" # GitHub Flavored Markdown, as used by GitHub Pages
gem "webrick", "~> 1.8" # required for `jekyll serve` on Ruby >= 3.0

# the plugins previously provided by the `github-pages` gem which this site uses
gem "jekyll-default-layout", "~> 0.2"
gem "jekyll-optional-front-matter", "~> 0.3"
gem "jekyll-readme-index", "~> 0.4"
gem "jekyll-relative-links", "~> 0.8"
gem "jekyll-titles-from-headings", "~> 0.5"

gem "html-proofer", "~> 5.0"
# `html-proofer` 5.2.2 calls `JSON.parse` with positional options, which the `json`
# gem dropped in version 3, breaking the `--typhoeus` option.
gem "json", "~> 2.7"
